"""Environmental Stewardship system for the AELMA twin."""

from .stewardship import (
    ALERT_EMISSIONS_BASELINE_PCT,
    ALERT_EFFICIENCY_MIN_NM_PER_GAL,
    ALERT_BYCATCH_RATIO_MAX_PCT,
    ALERT_WASTE_NONCOMPLIANCE_MAX_PCT,
    AlertSeverity,
    BycatchDisposition,
    BycatchEvent,
    CarbonFootprint,
    DisposalMethod,
    EMISSION_FACTORS,
    EmissionFactor,
    EnvironmentalStewardship,
    FuelRecord,
    FuelType,
    SustainabilityMetric,
    SUSTAINABILITY_TARGETS,
    WasteRecord,
    WasteType,
)

__all__ = [
    "EnvironmentalStewardship",
    "FuelRecord",
    "FuelType",
    "EmissionFactor",
    "CarbonFootprint",
    "WasteRecord",
    "WasteType",
    "DisposalMethod",
    "BycatchEvent",
    "BycatchDisposition",
    "SustainabilityMetric",
    "AlertSeverity",
    "EMISSION_FACTORS",
    "SUSTAINABILITY_TARGETS",
    "ALERT_EMISSIONS_BASELINE_PCT",
    "ALERT_EFFICIENCY_MIN_NM_PER_GAL",
    "ALERT_BYCATCH_RATIO_MAX_PCT",
    "ALERT_WASTE_NONCOMPLIANCE_MAX_PCT",
]
